### ISSUE TITLE
你这个 README 也忒简洁了吧

### ISSUE THREAD

**Issue by qinsJs** [fengivy/Weather#1]
这么好的思路  
这么好的view  
不应该多放两个截图么  

![](http://upload-images.jianshu.io/upload_images/837800-2f51695590a5c82b.gif?imageMogr2/auto-orient/strip)

**Comment by fengivy** [comment]
因为这个主要是希望大家能够通过文章知道思路而已，并不是开源的控件，所以主要是在博客分享，这里只是方便大家查看源码！
谢谢你的关注！！
