### ISSUE TITLE
小炸弹。。。脸和头分离了

### ISSUE THREAD

**Issue by suSUsu111** [fengivy/Weather#3]
小米2s上 笑脸在头上方，引线都没有

**Comment by findvoid** [comment]
<img width="409" alt="453b35dc-49e4-4d7e-8a7e-310222a1059d" src="https://user-images.githubusercontent.com/13435914/32142578-20d15622-bc68-11e7-9a79-bb87c377ddc3.png">

**Comment by fengivy** [comment]
@suSUsu111 @findvoid 问题已修复..
